### ISSUE TITLE
Crash when placing Arms Assistant

### ISSUE THREAD

**Issue by darthvader45** [Leviathan143/minecraft-quiverbow#2]
java.lang.NullPointerException: Ticking entity
	at com.domochevsky.quiverbow.AI.AI_Properties.sendInventoryToPlayersInRange(AI_Properties.java:62)
	at com.domochevsky.quiverbow.ArmsAssistant.Entity_AA.sendState(Entity_AA.java:282)
	at com.domochevsky.quiverbow.ArmsAssistant.Entity_AA.onLivingUpdate(Entity_AA.java:183)
	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2296)
	at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:344)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2119)
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:876)
	at net.minecraft.world.World.updateEntity(World.java:2085)
	at net.minecraft.world.World.updateEntities(World.java:1896)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:648)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:795)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:699)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548)
	at java.lang.Thread.run(Unknown Source)

**Comment by Daomephsta** [comment]
I know you're just trying to help, but this repo is NOT ready for testing. If I wanted it tested, I'd create a release and ask for testers. If I want help, I will ask for it.

**Comment by darthvader45** [comment]
Just something to fix before release.  It's otherwise perfectly functional from what I looked at.  Able to fire all weapons quite well, no lag, it's awesome.  I'd say just a little more polishing and then maybe a test release.

Sorry for pissing you off there, if I did...

**Comment by Daomephsta** [comment]
@darthvader45 
Dude, I already knew it was broken. I intend to completely rewrite the AA, because so much has changed.

**Comment by darthvader45** [comment]
Okay, thanks.  Just checking in on that.  As long as I know your intentions, that's good.  Is that pretty much the last thing?

**Comment by Daomephsta** [comment]
@darthvader45 
No, however all you can do now is wait. I will ask for help when I need it.

**Comment by darthvader45** [comment]
Okay, let me know.
